### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by b0123456789** [ThexXTURBOXx/dex2jar#13]
dex2jar ../com.ss.android.ugc.aweme.lite.apk -> .\com.ss.android.ugc.aweme.lite-dex2jar.jar
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.StringBuilder.toString(Unknown Source)
        at com.googlecode.d2j.util.Mutf8.decode(Mutf8.java:42)
        at com.googlecode.d2j.reader.DexFileReader.getString(DexFileReader.java:1034)
        at com.googlecode.d2j.reader.DexFileReader.getType(DexFileReader.java:1044)
        at com.googlecode.d2j.reader.DexFileReader.getMethod(DexFileReader.java:1022)
        at com.googlecode.d2j.reader.DexFileReader.acceptInsn(DexFileReader.java:1728)
        at com.googlecode.d2j.reader.DexFileReader.acceptCode(DexFileReader.java:1489)
        at com.googlecode.d2j.reader.DexFileReader.acceptMethod(DexFileReader.java:1142)
        at com.googlecode.d2j.reader.DexFileReader.acceptClass(DexFileReader.java:918)
        at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:725)
        at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:122)
        at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:115)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:48)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:235)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:103)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:297)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:16)

**Comment by coco101000000000** [comment]
app download address:

http://221.179.41.80:49155/imtt.dd.qq.com/16891/apk/534543437451773FE790418EDFF9DEBE.apk?mkey=616663c8bd8f2b9a701b0cfc50299528&arrive_key=10168902610&fsname=com.baidu.searchbox.lite_5.16.0.11_28312960.apk&cip=183.238.72.89&proto=http

**Comment by coco101000000000** [comment]
linux run success ,nut window not.
