### ISSUE TITLE
What is the best Method to edit the code of an apk?

### ISSUE THREAD

**Issue by tiredElephant** [ThexXTURBOXx/dex2jar#40]
I created the jar and can read it with jd-gui but I cannot edit it.

I don't know what to do with the jar now. 
I would like to be able to edit the code. I don't know Java bytecode but would be open to learn it if necessary. 
Does anybody have any tips on getting started modifying the code of android apps?

I don't know where else to post it.

I tried converting it to jasmin but it fails with this error:

`Exception in thread "main" java.lang.NoSuchMethodError: 'void org.objectweb.asm.util.Printer.appendString(java.lang.StringBuilder, java.lang.String)'
        at com.googlecode.d2j.jasmin.JasminDumper.print(JasminDumper.java:618)
        at com.googlecode.d2j.jasmin.JasminDumper$1.visitLdcInsn(JasminDumper.java:410)
        at org.objectweb.asm.tree.LdcInsnNode.accept(LdcInsnNode.java:71)
        at com.googlecode.d2j.jasmin.JasminDumper.dump(JasminDumper.java:296)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd.disassemble1(Jar2JasminCmd.java:108)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd.access$000(Jar2JasminCmd.java:21)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd$1.visitFile(Jar2JasminCmd.java:92)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd$1.visitFile(Jar2JasminCmd.java:88)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd.travelFileTree(Jar2JasminCmd.java:88)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd.disassemble0(Jar2JasminCmd.java:82)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd.doCommandLine(Jar2JasminCmd.java:67)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:297)
        at com.googlecode.d2j.jasmin.Jar2JasminCmd.main(Jar2JasminCmd.java:37)`

Is this even a good approach to editing the code?

I hope somebody will be able to help me

**Comment by ThexXTURBOXx** [comment]
Hi, GitHub issues are not the right place for asking questions.
If you need to `edit` the code, use either BytecodeViewer or Recaf instead.
However, I will leave this issue open because of the exception

**Comment by ThexXTURBOXx** [comment]
The error is not reproducible on my end. Please try redownloading the [https://github.com/ThexXTURBOXx/dex2jar/releases/latest](latest release).
