### ISSUE TITLE
d2j-jar2dex: UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by jadkorr** [ThexXTURBOXx/dex2jar#52]
$HOME/Documents/dex-tools-2.4.21/d2j-jar2dex.sh -s 24 classes-dex2jar.jar
jar2dex classes-dex2jar.jar -> classes-dex2jar-jar2dex.dex
call com.android.dx.command.Main.main[--dex, --no-strict, --output=/Users/User/Documents/July2024/App/Testing/Android/workshop/App11/classes-dex2jar-jar2dex.dex, --min-sdk-version=24, /Users/User/Documents/July2024/App/Testing/Android/workshop/App11/classes-dex2jar.jar]
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
	at com.android.dx.command.dexer.Main.main(Main.java:244)
	at com.android.dx.command.Main.main(Main.java:95)
	at com.googlecode.dex2jar.tools.Jar2Dex.doCommandLine(Jar2Dex.java:95)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:297)
	at com.googlecode.dex2jar.tools.Jar2Dex.main(Jar2Dex.java:16)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
	... 7 more

**Comment by ThexXTURBOXx** [comment]
This looks like it wouldn't be very easy to fix since it is a very internal issue within `dx`.
Maybe, an update of the `dx` library would be the solution, but this would break Java 8 support, sadly.
So, I will leave this as-is for now. If you want to try out whether updating `dx` works, you can try that out locally

**Comment by jadkorr** [comment]
Thank you @ThexXTURBOXx will try it to see how it goes

**Comment by JhinSir** [comment]
> Thank you @ThexXTURBOXx will try it to see how it goes

Did you solve it in the end? I also encountered this problem. Can I replace dx with d8 to solve it?

**Comment by ThexXTURBOXx** [comment]
@JhinSir I have also seen your other issue, but this is sadly out of the scope of dex2jar. You can indeed replace dx with d8, but you will need a major rewrite to make that work.

**Comment by JhinSir** [comment]
> @JhinSir I have also seen your other issue, but this is sadly out of the scope of dex2jar. You can indeed replace dx with d8, but you will need a major rewrite to make that work.

Yes, I have solved the problem mentioned in the issue. It is not a dex2Jar problem. I am very sorry!! But the problem I have encountered with dex2Jar is the one mentioned in this issue!! Is there any other solution besides d8?

**Comment by JhinSir** [comment]
Yes, I have solved the problem mentioned in the issue. It is not a dex2Jar problem. I am very sorry!! But the problem I have encountered with dex2Jar is the one mentioned in this issue!! Is there any other solution besides d8?
















At 2024-09-13 17:01:06, "Nico Mexis" ***@***.***> wrote:

@JhinSir I have also seen your other issue, but this is sadly out of the scope of dex2jar. You can indeed replace dx with d8, but you will need a major rewrite to make that work.
